
// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package web3helper

import (

)

const (
	// GenerateContractEventSubscription etc etc.
	GenerateContractEventSubscription = "GenerateContractEventSubscription"

	// SuggestGasPriceException etc etc.
	SuggestGasPriceException = "SuggestGasPriceException"
)